# Uncomment this line to define a global platform for your project
 platform :ios, '10.0'

source 'https://github.com/LKModulizationDemo/ConfigPrivatePod.git'
#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'MainProject' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 
  # Private Pods
  pod 'HandyFrame'
  pod "CTMediator"
  

  pod 'A_Category'
  pod "A"
#  pod 'A', :git => 'https://github.com/LKModulizationDemo/A.git'

  pod "B_Category"

#本地
#  pod 'A_Category', :path => '../../A_Category'
#  pod "B_Category", :path => "../../B_Category"
#  pod "A", :path => "../../A"

end
